language: python
python:
  - "2.7"
  - "3.3"
install: 
  - pip install -r requirements/ci.txt --use-mirrors
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=stagecraft.settings.ci SECRET_KEY=xyz DATABASE_URL=postgres://a:b@foo:999/db
  global:
    # NOTE: contains GH_TOKEN=xxx from github user gds-pp-ci
    secure: AnhgvS32/AMPi8rl9L9xh/2Xmt1459jXs13eiJI4kHtSGP/n2gkZtfKTiU9wezNqI5tVk4fYYltJNjvk5ZGkiEm/z5vpp8urRHUcGejZaa6ziyzFALpftuI5/5TF/dnlowQdFjh4Tcx4crZ1u5l4z5eJoxUSd4x9hk4d8/Tnjj8=
script:
  - ./run_tests.sh
after_script:
  - coveralls
after_success:
  - ./.travis_scripts/push_release_tag.sh
branches:
  except:
    - release
    - /^release_\d+$/
notifications:
  email: false
